### PR TITLE
include generated source

### PR DESCRIPTION
**Pull request by elianiva**
This is needed for Neovim to be able to get the generated source directly so the user won't need to install tree-sitter-cli and generate the parser themself.

This was generated using tree-sitter-cli v0.20.0

### CODE REVIEW

**Comment by theHamsta** [comment]
You could also add a `requires_generate_from_source a= true`

**Comment by elianiva** [comment]
yes, but that needs `grammar.js` and that's not in the repo. I think @LumaKernel removed grammar.js in 8778ddcb because the repo has grammar.ts. I was also thinking about adding grammar.js back before I made this PR but I thought including the generated parser would be more convenient for most users. Not 100% sure to be honest.

**Comment by LumaKernel** [comment]
Thanks for PR. I will take a time to look into.
If you can afford, please let me know how to integrate with nvim with this PR.

**Comment by elianiva** [comment]
Either add `grammar.js` or include the generated parser, or both.

If we were to include `grammar.js` then whoever wants to use this parser in Neovim must have a C compiler _and_ the `tree-sitter-cli` which is a bit inconvenient, I think. I'm not sure why would someone need to generate the `parser.c` except if there's an ABI change from tree-sitter.

The second option is to include the generated `parser.c`, which this PR is trying to do. Whoever wants to use it will only need a C compiler, but the size of the repo would get a bit bigger and I don't think that's much of an issue.

Having both `grammar.js` and `grammar.ts` would be kinda weird since they could get out of sync? If we want to keep the type definition, I could probably convert the typescript definition into jsdoc so whoever wants to edit `grammar.js` would still get autocompletions.

**Comment by theHamsta** [comment]
Wouldn't the translation to JS happen on `npm install`? Nvim-treesitter supports running npm before `tree-sitter generate`

I suppose it would also be ok to add a `npm run xxxx` to package.json that does the necessary magic for nvim-treesitter

**Comment by elianiva** [comment]
hmm, yeah, I think we can do that instead. It needs to run `npm install` and then `npm run build` to generate the grammar.js and the parser. Does nvim-treesitter support running npm scripts before compiling the parser? I can't find anything about that.

**Comment by theHamsta** [comment]
At the moment it only supports running `npm install` (see install.lua). But support for npm scripts could be added.

**Comment by theHamsta** [comment]
I'll create a PR for supporting npm scripts

**Comment by elianiva** [comment]
closing this because this is no longer needed

**Pull request closed without merging**
